name: bettergas_assignment
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  lottie: ^3.0.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.7
  google_places_flutter_api: ^1.0.2
  package_info_plus: ^4.2.0
  google_api_headers: ^2.0.0
  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  
flutter_launcher_icons:
  image_path: "assets/Logo_without_descri.png"
  android: true
  ios: true
  remove_alpha_ios: true
  

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - animations/
    - assets/icons/

